Categories:
  - System
License: MIT
SourceCode: https://github.com/p0isonra1n/Doze-Settings-Editor
IssueTracker: https://github.com/p0isonra1n/Doze-Settings-Editor/issues

AutoName: Doze Editor
Description: |-
    Simple editor of the settings or parameters which affect the operation of Doze.
    A list of parameters and corresponding descriptions is available in the
    <a href="https://github.com/p0isonra1n/Doze-Settings-Editor/blob/HEAD/README.md">README</a>.

RequiresRoot: 'yes'

RepoType: git
Repo: https://github.com/p0isonra1n/Doze-Settings-Editor

Builds:
  - versionName: '6.0'
    versionCode: 6
    disable: Missing res, see https://github.com/p0isonra1n/Doze-Settings-Editor/issues/2
    commit: f424bce4641dfd14181d5770701405417f6114d6
    subdir: app
    gradle:
      - yes
    srclibs:
      - RootTools@4.2
      - RootShell@1.3
    rm:
      - app/libs/*.jar
    prebuild:
      - sed -i -e '/RootShell/d' build.gradle
      - cp -fR $$RootShell$$/src/com  src/main/java/

AutoUpdateMode: None
UpdateCheckMode: RepoManifest
CurrentVersion: '6.0'
CurrentVersionCode: 6
