Categories:
  - Navigation
License: GPL-2.0-only
WebSite: http://aagtl.work.zoff.cc
SourceCode: https://aagtl.zoffcc.com/aagtl_public1

AutoName: aagtl
Description: |-
    Loosely based on AGTL, a geocaching app for Maemo/Meego. This uses info from
    geocaching.com so you will need an account there. Works completely offline (if
    you download the cache details beforehand) and uses OpenStreetMap maps.

RepoType: git-svn
Repo: https://aagtl.zoffcc.com/aagtl_public1

Builds:
  - versionName: 1.0.30
    versionCode: 30
    disable: Location of corresponding source not obvious
    commit: unknown - see disabled

  - versionName: 1.0.31
    versionCode: 31
    commit: '3'

  - versionName: 1.0.36
    versionCode: 36
    commit: '4'

AutoUpdateMode: None
UpdateCheckMode: RepoManifest
CurrentVersion: 1.0.36
CurrentVersionCode: 36
